version: '3'
services:
  node_app:
    container_name: atsource_app
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: sh -c "npm install && node app.js"
    restart: unless-stopped 